### ISSUE TITLE
Why not compatible with iOS6?

### ISSUE THREAD

**Issue by MonaDogg** [Quotation/WhoCall#1]
I will try to do this work.

**Comment by sunkehappy** [comment]
我还没看源代码，不确定，你可以先看下他们的源代码然后尝试一下。或者等作者来指条明路。

另外，为什么你们不用英语呢？中文在这里不是那么通用的。

**Comment by MonaDogg** [comment]
Because of my poor english.... :)

**Comment by Quotation** [comment]
@MonaDogg 因为这个App是靠语音提醒的，不是在来电的界面显示文字。而语音合成的API是iOS7才加的。
@sunkehappy 因为这个App的大部分功能只对中国电话号码有效。

**Comment by Quotation** [comment]
嗯我打算支持iOS 6了，有几个功能是可以给iOS 6用的。

**Comment by MonaDogg** [comment]
很棒,期待
