### ISSUE TITLE
来电归属地的数据库记录不全

### ISSUE THREAD

**Issue by lanvige** [Quotation/WhoCall#10]
刚把同事的手机号在数据库里找了下，发现一大半的都没有记录。请问你的数据库是从哪里来的，我看看能不能找个新点的库。

**Comment by Quotation** [comment]
这里的 https://github.com/roymax/moquery/tree/master/db，再自己删除了一些冗余的数据。确实是挺老的数据了。

这里有新的库http://duanmu.org/log/mobile/，但是是MDB格式的，我没有Access，打不开 -_-。如果你能帮忙转成sqlite格式那就太感谢了。

**Comment by Quotation** [comment]
更新至2013年12月的数据库了。
