### ISSUE TITLE
方便告诉这些是怎么得来的吗？谢谢

### ISSUE THREAD

**Issue by mrdaios** [Quotation/WhoCall#14]
// encrypted string's
# define ENCSTR_kCTCallStatusChangeNotification  [@"n0AHD2SfoSA0LKE1p0AbLJ5aMH5iqTyznJAuqTyiot==" wcDecryptString]
# define ENCSTR_kCTCall                          [@"n0AHD2SfoN==" wcDecryptString]
# define ENCSTR_kCTCallStatus                    [@"n0AHD2SfoSA0LKE1pj==" wcDecryptString]
# define ENCSTR_CTTelephonyCenterGetDefault      [@"D1EHMJkypTuioayQMJ50MKWUMKERMJMuqJk0" wcDecryptString]
# define ENCSTR_CTTelephonyCenterAddObserver     [@"D1EHMJkypTuioayQMJ50MKWOMTECLaAypaMypt==" wcDecryptString]
# define ENCSTR_CTTelephonyCenterRemoveObserver  [@"D1EHMJkypTuioayQMJ50MKWFMJ1iqzICLaAypaMypt==" wcDecryptString]
# define ENCSTR_CTCallCopyAddress                [@"D1EQLJkfD29jrHSxMUWyp3Z=" wcDecryptString]
# define ENCSTR_CTCallDisconnect                 [@"D1EQLJkfETymL29hozIwqN==" wcDecryptString]

**Comment by Quotation** [comment]
例如第一行，就是调用`wcEncryptString`加密得到的字符串。见`Src/WCUtil.m`。
而kCTCallStatusChangeNotification这些定义是私有API，网上能搜到。

**Comment by mrdaios** [comment]
好的，谢谢，等下学习看看！

发自我的 iPhone

在 2014年2月26日，上午10:06，Xiaolei Wang notifications@github.com 写道：

例如第一行，就是调用wcEncryptString加密得到的字符串。见Src/WCUtil.m。
而kCTCallStatusChangeNotification这些定义是私有API，网上能搜到。

**Comment by app111** [comment]
求楼主《Xiaolei Wang》联系方式，我在做这个项目扩展

**Comment by app111** [comment]
楼主，我在做这个项目扩展，数据库生成工具有吗？

**Comment by Quotation** [comment]
归属地数据是从这来的：http://duanmu.org/log/mobile/
数据是ACCESS格式，用工具转成SQLite，再手工去掉一些不需要的列。

**Comment by app111** [comment]
好的，非常感谢！我再找找诈骗，响一声电话的接口

在 2014年5月14日，下午8:39，Xiaolei Wang notifications@github.com 写道：
