### ISSUE TITLE
发现是推销电话直接屏蔽如何？

### ISSUE THREAD

**Issue by lexrus** [Quotation/WhoCall#4]
然后发一个静音的本地推送。

**Comment by Quotation** [comment]
好主意，等我加个选项。

**Comment by Quotation** [comment]
悲剧了，代码都写好之后，测试的时候发现……CTCallDisconnect在iOS 7上不能用了。
http://stackoverflow.com/questions/19101563/ios-7-private-api-to-disconnect-calls-ctcalldisconnect-does-not-work

**Comment by Quotation** [comment]
代码commit了，但是现在没法使用，等App支持了iOS 6再说。
