### ISSUE TITLE
非开发人员如何使用呢？

### ISSUE THREAD

**Issue by jcpplus** [Quotation/WhoCall#7]
请问若没有开发者账号，如何进行安装？是否可以通过类似xx助手等来进行下载安装呢。

已经通过作者的推里找到了ota链接，不知普通账号能否使用http://ota.uibutton.com/whocall/

**Comment by flyingbird** [comment]
找个企业版账号签署。

**Comment by Quotation** [comment]
楼上贴的OTA地址不是我搞的，我也不知道那个是用的什么证书。如果是企业版开发账号的证书，就可以给普通用户装了。
或者找个你周围的开发者帮你装上。

**Comment by jcpplus** [comment]
@Quotation sorry，原来的地址我稍候再找下来源。多谢。
是在这里看到的这个OTA：https://twitter.com/lexrus  
，大概20小时前发的推
